---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
activity <- read.csv(file="activity.csv", header=TRUE)
head(activity, 2)
str(activity)


## What is mean total number of steps taken per day?
tot_steps <- activity %>% group_by(date) %>% filter(!is.na(steps)) %>%
      summarize(tot_steps = sum(steps, na.rm = TRUE))
summary(tot_steps$tot_steps) ##  or 
avg_steps <- mean(tot_steps$tot_steps, na.rm = TRUE)
avg_steps # 10766.19
median_steps <- median(tot_steps$tot_steps, na.rm = TRUE)
median_steps # 10765
# Make a histogram of the total number of steps taken per day
ggplot(tot_steps, aes(tot_steps)) + geom_histogram(binwidth = 2500, fill = "darkgreen", col = "lightgreen") +
      labs(title = "Daily Steps Histogram", x = "Total Steps per Day", y = "Number of Days")

## What is the average daily activity pattern?
step_int <- activity %>% group_by(interval) %>% filter(!is.na(steps)) %>%
      summarize(int_steps = mean(steps, na.rm = TRUE))
head(step_int, 2)
str(step_int)

summary(step_int)

ggplot(step_int, aes(interval, int_steps)) + geom_line() +
      labs(title = "Daily Average Activity", x = "Interval", y = "Average Steps")
# Interval with most steps   
step_int[which.max(step_int$int_steps), ] # 835 which means 8:35-8:40

## Imputing missing values
# Summary of missing values
colSums(is.na(activity)) # 2304 missing steps values, 0 missing date values, 0 missing interval values

# Add mean value for that interval into original dataset replacing NA values
fj_int <- activity
fj_int_steps <- full_join(fj_int, step_int, by = 'interval')
nas <- is.na(fj_int$steps)
fj_int_steps[nas,]$steps <- fj_int[nas, ]$int_steps
filled_int_steps <- select(fj_int_steps, steps = steps, date, interval)
filled_int_steps_date <- filled_int_steps %>% group_by(date)
head(filled_int_steps_date, 5)
colSums(is.na(filled_int_steps_date))

filled_tot_steps <- summarize(filled_int_steps_date, total_steps = sum(steps))

ggplot(filled_tot_steps, aes(total_steps)) + geom_histogram(binwidth = 2500, fill = "darkblue", col = "lightblue") +
      labs(title = "Daily Steps Histogram", x = "Total Steps per Day", y = "Number of Days")

summary(filled_tot_steps)


## Are there differences in activity patterns between weekdays and weekends?
filled_int_steps_date <- mutate(filled_int_steps_date, weekend = factor(weekdays(ymd(date)) %in% c('Saturday', 'Sunday')))
filled_tot_steps_wk <- group_by(filled_int_steps_date, weekend, interval)
filled_tot_steps_wk_int <- summarize(filled_tot_steps_wk, steps = mean(steps))

gplot1 <- filled_tot_steps_wk_int %>% filter(weekend == TRUE)
ggplot(gplot1, aes(interval, steps)) + geom_line() + labs(title = "Weekends", x = "Average Interval Steps per Day",
                                                          y = "# of Steps")
gplot2 <- filled_tot_steps_wk_int %>% filter(weekend == FALSE)
ggplot(gplot2, aes(interval, steps)) + geom_line() + labs(title = "Weekdays", x = "Average Interval Steps per Day",
                                                          y = "# of Steps")
